import os
import pickle
import gc
from sklearn.preprocessing import LabelEncoder
from model_utils import evaluate_outlier_filters, plot_ml_results, set_global_determinism

set_global_determinism(0)

exp_path = "/Users/kautsarg/Documents/Final Project/Run Data/trial test data/D20250808_E00_C00_F4500KHz_U_Sample_7"
data_path = os.path.join(exp_path, "curve_for_training_updated.pkl")
results_file_path = os.path.join(exp_path, "all_ml_results_dynamic.pkl")

with open(data_path, 'rb') as f:
    training_data = pickle.load(f)

dataset_name = training_data["dataset_name"]
dataset = training_data["dataset"]
kinetic_features = training_data["kinetic_features"]
Y_well = training_data["Y_well"]

encoder = LabelEncoder()
y_full = encoder.fit_transform(Y_well)

# 1. Dynamically gather all filter columns generated by the extraction script
all_columns = kinetic_features[0].columns.tolist()
outlier_filters = [None] + [c for c in all_columns if 'label' in c and ('msc_' in c or 'amf_' in c or 'mean_std_' in c)]

print(f"[*] Found {len(outlier_filters)-1} Dynamic Outlier Filters to test.")

if os.path.exists(results_file_path):
    with open(results_file_path, 'rb') as f:
        all_ml_results = pickle.load(f)
else:
    all_ml_results = {}

for idx, (name, features_df, curves_2d) in enumerate(zip(dataset_name, kinetic_features, dataset)):
    clean_title = name.replace("_", " ").title()
    if clean_title not in all_ml_results: all_ml_results[clean_title] = {}
    
    # NATIVE TRAINING
    if "Native" not in all_ml_results[clean_title]:
        res = evaluate_outlier_filters(curves_2d, features_df, y_full, outlier_filters, clean_title, "Native")
        all_ml_results[clean_title]["Native"] = res
        with open(results_file_path, 'wb') as f: pickle.dump(all_ml_results, f)
        
    # REFERENCE TRAINING (Using dataset[0])
    if "Reference" not in all_ml_results[clean_title]:
        res = evaluate_outlier_filters(dataset[0], features_df, y_full, outlier_filters, clean_title, "Reference")
        all_ml_results[clean_title]["Reference"] = res
        with open(results_file_path, 'wb') as f: pickle.dump(all_ml_results, f)
        
    gc.collect()

print("Training Complete!")