#!/bin/bash
#PBS -N chip_pipeline_manual
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=8:mem=32gb:ngpus=1
#PBS -J 0-10
#PBS -o /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/chip_lab_pipeline_manual/
#PBS -e /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/chip_lab_pipeline_manual/
#PBS -k eo

set -e

mkdir -p /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/chip_lab_pipeline_manual

# Load modules
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

# Activate venv
source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate

export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"

cd /rds/general/user/gk225/home/POC_DDM/gk_code/main

REAL_TASK_ID=$((PBS_ARRAY_INDEX))

EXP_FOLDER=/rds/general/user/gk225/home/POC_DDM_datasets/POC_DDM_datasets/POC_DDM_chip_init

TRAIN_FOLDER="$EXP_FOLDER"

python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/01_curve_preprocessing_v6.py --task_id $REAL_TASK_ID --exp_folder "$EXP_FOLDER" --n_wells 10 --n_a_type v06 --force_rerun
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/02_outlier_detection_pipeline.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/03_main_training.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --n_splits 1 --force_rerun
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/05_outlier_visualization_report.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/06_model_prediction_report.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/07_attribution_vis_all.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun

deactivate
