#!/bin/bash
#PBS -N ddm_e2e_pipeline
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=8:mem=64gb:ngpus=1
#PBS -o output.log
#PBS -e error.log

module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

# Activate  virtual environment
source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate

# Run scripts sequentially
# export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"

cd /rds/general/user/gk225/home/POC_DDM/gk_code
python /rds/general/user/gk225/home/POC_DDM/gk_code/data_analysis_and_viz.py 

cd /rds/general/user/gk225/home/POC_DDM/gk_code/legacy
python /rds/general/user/gk225/home/POC_DDM/gk_code/legacy/master_outlier_detection_pipeline.py
python /rds/general/user/gk225/home/POC_DDM/gk_code/legacy/main_training.py

# Deactivate virtual environment
deactivate