#!/bin/bash
#PBS -N ddm_parallel_array
#PBS -l walltime=48:00:00      

# Request resources for a single job
#PBS -l select=1:ncpus=8:mem=64gb:ngpus=1

# Launch 12 clones of this job (PBS_ARRAY_INDEX indices 1 through 12)
#PBS -J 1-12

#PBS -o logs/
#PBS -e logs/              

cd /rds/general/user/gk225/home/POC_DDM

# Load modules
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

# Activate venv
source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate

export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"

cd /rds/general/user/gk225/home/POC_DDM/gk_code
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/data_analysis_and_viz-par.py $PBS_ARRAY_INDEX

cd /rds/general/user/gk225/home/POC_DDM/gk_code/legacy
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/legacy/master_outlier_detection_pipeline-par.py $PBS_ARRAY_INDEX
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/legacy/main_training-par.py $PBS_ARRAY_INDEX

deactivate