#!/bin/bash
#PBS -N e2e_ddm_pipeline
#PBS -l walltime=24:00:00      

# Request resources for a single job
#PBS -l select=1:ncpus=8:mem=32gb:ngpus=1

# Launch 12 clones of this job (PBS_ARRAY_INDEX indices 1 through 12)
#PBS -J 1-15

#PBS -o logs/
#PBS -e logs/              

cd /rds/general/user/gk225/home/POC_DDM

# Load modules
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

# Activate venv
source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate

export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"

# Run python script
cd /rds/general/user/gk225/home/POC_DDM/gk_code/main

PY_INDEX=$(($PBS_ARRAY_INDEX - 1))

# python -u /rds/general/user/gk225/home/POC_DDM/gk_code/legacy/01_par-curve_preprocessing.py --task_id $PY_INDEX
# python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/02_outlier_detection_pipeline.py --task_id $PY_INDEX
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/03_main_training.py --task_id $PY_INDEX --n_splits 10

deactivate