#!/bin/bash
#PBS -N multi_lofo_crossval
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=16:mem=64gb:ngpus=1
#PBS -J 0-1
#PBS -o logs/
#PBS -e logs/

# Safety check: PBS will fail if the logs directory doesn't exist
mkdir -p /rds/general/user/gk225/home/POC_DDM/logs

# Load modules
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

# Activate venv
source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate

export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"
cd /rds/general/user/gk225/home/POC_DDM/gk_code/main

if [ "$PBS_ARRAY_INDEX" -eq 0 ]; then
    python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/04_cross_dataset_training.py --exp_folder /rds/general/user/gk225/home/POC_DDM_datasets/POC_DDM_datasets/POC_DDM_multi_nc_subtract/ --task_id $PBS_ARRAY_INDEX
else
    python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/04_cross_dataset_training.py --exp_folder /rds/general/user/gk225/home/POC_DDM_datasets/POC_DDM_datasets/POC_DDM_multi/ --task_id $PBS_ARRAY_INDEX
fi

deactivate