#!/bin/bash
#PBS -N multi_full_pipeline
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=8:mem=32gb:ngpus=1
#PBS -J 2-6
#PBS -o /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/multi_full_pipeline/
#PBS -e /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/multi_full_pipeline/
#PBS -k eo

mkdir -p /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/multi_full_pipeline

# Load modules
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

# Activate venv
source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate
export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"

cd /rds/general/user/gk225/home/POC_DDM/gk_code/main

REAL_TASK_ID=$((8-PBS_ARRAY_INDEX))
EXP_FOLDER=/rds/general/user/gk225/home/POC_DDM_datasets/POC_DDM_datasets/POC_DDM_multi

for nc_subtract in 0 1; do
    if [ "$nc_subtract" -eq 1 ]; then
        # python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/01_curve_preprocessing_v6.py --task_id $REAL_TASK_ID --exp_folder "$EXP_FOLDER" --n_wells 10 --n_a_type v06 --nc_subtract  --force_rerun
        TRAIN_FOLDER="${EXP_FOLDER}_nc_subtract"
    else
        # python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/01_curve_preprocessing_v6.py --task_id $REAL_TASK_ID --exp_folder "$EXP_FOLDER" --n_wells 10 --n_a_type v06 --force_rerun
        TRAIN_FOLDER="$EXP_FOLDER"
    fi

    echo "################################################################################"
    echo $TRAIN_FOLDER
    echo "################################################################################"
    
    # python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/02_outlier_detection_pipeline.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun
    python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/03_main_training.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --n_splits 1
    python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/05_outlier_visualization_report.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun
    python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/06_model_prediction_report.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun
    python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/07_attribution_vis_all.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun

done

deactivate
