#!/bin/bash
#PBS -N multi_04_loco_crossval
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=8:mem=32gb:ngpus=1
#PBS -J 0-0
#PBS -o logs/
#PBS -e logs/

cd /rds/general/user/gk225/home/POC_DDM

# Load modules
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

# Activate venv
source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate

export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"
cd /rds/general/user/gk225/home/POC_DDM/gk_code/main

# python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/02_outlier_detection_pipeline.py --task_id $PBS_ARRAY_INDEX --exp_folder /rds/general/user/gk225/home/POC_DDM_datasets/POC_DDM_chip_init
python  -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/04_cross_dataset_training.py --exp_folder /rds/general/user/gk225/home/POC_DDM_datasets/POC_DDM_multi_nc_subtract/ --task_id $PBS_ARRAY_INDEX

deactivate
