#!/bin/bash
#PBS -N new_xai_test
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=8:mem=32gb:ngpus=1
#PBS -o /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/new_xai_test/
#PBS -e /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/new_xai_test/
#PBS -k eo

set -e

mkdir -p /rds/general/user/gk225/home/POC_DDM/hpc_jobs/logs/new_xai_test

module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/12.6.0
module load cuDNN/9.10.2.21-CUDA-12.6.0

source /rds/general/user/gk225/home/venv_poc_ddm/bin/activate
export PYTHONPATH="/rds/general/user/gk225/home/POC_DDM:/rds/general/user/gk225/home/POC_DDM/gk_code:$PYTHONPATH"
cd /rds/general/user/gk225/home/POC_DDM/gk_code/main

TASK_ID=3
REAL_TASK_ID=$((8-TASK_ID))

EXP_FOLDER=/rds/general/user/gk225/home/refactor/POC_DDM_datasets/POC_DDM_multi
TRAIN_FOLDER="${EXP_FOLDER}_nc_subtract"

python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/07_attribution_vis_all.py --task_id $REAL_TASK_ID --exp_folder "$TRAIN_FOLDER" --force_rerun
python -u /rds/general/user/gk225/home/POC_DDM/gk_code/main/07b_cross_dataset_attribution_vis.py --exp_folder "$TRAIN_FOLDER" --filter_key None --force_rerun

deactivate
